package Model;
// Generated May 27, 2016 5:26:42 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * MediaLog generated by hbm2java
 */
public class MediaLog  implements java.io.Serializable {


     private Integer id;
     private Integer idUser;
     private Integer idItem;
     private BigDecimal rating;
     private BigDecimal timeSpent;
     private Date dateFinished;

    public MediaLog() {
    }

    public MediaLog(Integer idUser, Integer idItem, BigDecimal rating, BigDecimal timeSpent, Date dateFinished) {
       this.idUser = idUser;
       this.idItem = idItem;
       this.rating = rating;
       this.timeSpent = timeSpent;
       this.dateFinished = dateFinished;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public Integer getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(Integer idItem) {
        this.idItem = idItem;
    }
    public BigDecimal getRating() {
        return this.rating;
    }
    
    public void setRating(BigDecimal rating) {
        this.rating = rating;
    }
    public BigDecimal getTimeSpent() {
        return this.timeSpent;
    }
    
    public void setTimeSpent(BigDecimal timeSpent) {
        this.timeSpent = timeSpent;
    }
    public Date getDateFinished() {
        return this.dateFinished;
    }
    
    public void setDateFinished(Date dateFinished) {
        this.dateFinished = dateFinished;
    }




}


