package Model;
// Generated May 27, 2016 5:26:42 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * MediaLog generated by hbm2java
 */
public class MediaLog  implements java.io.Serializable {


     private int id;
     private User user;
     private Medium medium;
     private String item;
     private Double rating;
     private Double timeSpent;
     private Date dateFinished;

    public MediaLog() {
    }

    public MediaLog(User user, Medium medium, String item, Double rating, Double timeSpent, Date dateFinished) {
       this.user = user;
       this.medium = medium;
       this.item = item;
       this.rating = rating;
       this.timeSpent = timeSpent;
       this.dateFinished = dateFinished;
    }
    
    public Medium getMedium() {
        return this.medium;
    }
    
    public void setMedium(Medium medium) {
        this.medium = medium;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public Double getRating() {
        return this.rating;
    }
    
    public void setRating(Double rating) {
        this.rating = rating;
    }
    public Double getTimeSpent() {
        return this.timeSpent;
    }
    
    public void setTimeSpent(Double timeSpent) {
        this.timeSpent = timeSpent;
    }
    public Date getDateFinished() {
        return this.dateFinished;
    }
    
    public void setDateFinished(Date dateFinished) {
        this.dateFinished = dateFinished;
    }




}


