package Model;
// Generated May 27, 2016 5:26:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String nameUser;
     private String password;
     private Date dateBirth;
     private String email;

    public User() {
    }

	
    public User(String nameUser, String password, String email) {
        this.nameUser = nameUser;
        this.password = password;
        this.email = email;
    }
    public User(String nameUser, String password, Date dateBirth, String email) {
       this.nameUser = nameUser;
       this.password = password;
       this.dateBirth = dateBirth;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNameUser() {
        return this.nameUser;
    }
    
    public void setNameUser(String nameUser) {
        this.nameUser = nameUser;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDateBirth() {
        return this.dateBirth;
    }
    
    public void setDateBirth(Date dateBirth) {
        this.dateBirth = dateBirth;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


