package Model;
// Generated May 27, 2016 5:26:42 PM by Hibernate Tools 4.3.1


import Controller.HibernateUtil;
import java.util.Date;
import java.util.List;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String nameUser;
     private String password;
     private Date dateBirth;
     private String email;

    public User() {
    }

	
    public User(String nameUser, String password, String email) {
        this.nameUser = nameUser;
        this.password = password;
        this.email = email;
    }
    public User(String nameUser, String password, Date dateBirth, String email) {
       this.nameUser = nameUser;
       this.password = password;
       this.dateBirth = dateBirth;
       this.email = email;
    }
   
    public Integer getUserByNameAndPassword(String name, String password)
    {
        Integer id = 0;
        String query = "from User user where user.email = '"+name+"' and user.password = '"+password+"'";
        System.out.println(query);
        List<User> list = executeHQLQuery(query);
        if(list.get(0).id != null)
        {
            id = list.get(0).getId();
        }
        return id;
    }
    
    public User getUserById(Integer id)
    {
        String query = "from User where id="+id;
        List<User> list = executeHQLQuery(query);
        return list.get(0);
    }
    
    private List executeHQLQuery(String hql) 
    {
        try 
        {
            Session session = HibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            Query q = session.createQuery(hql);
            List resultList = q.list();
            session.getTransaction().commit();
            return resultList;
        } 
        catch (HibernateException he) 
        {
            he.printStackTrace();
        }
        return null;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNameUser() {
        return this.nameUser;
    }
    
    public void setNameUser(String nameUser) {
        this.nameUser = nameUser;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDateBirth() {
        return this.dateBirth;
    }
    
    public void setDateBirth(Date dateBirth) {
        this.dateBirth = dateBirth;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


